force-app/main/default/objects/Quote__c/Quote__c.object-meta.xml
<CustomObject>
    <label>Quote</label>
    <nameField>
        <displayFormat>QI-{0000}</displayFormat>
        <label>Quote ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Quote__c/fields/Quote_Topic__c.field-meta.xml
<CustomField>
    <fullName>Quote_Topic__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Quote Topic</label>
    <referenceTo>Quote_Topic__c</referenceTo>
    <relationshipLabel>Quotes</relationshipLabel>
    <relationshipName>Quotes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Quote_Topic__c/Quote_Topic__c.object-meta.xml
<CustomObject>
    <label>Quote Topic</label>
    <nameField>
        <label>Quote Topic Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Quote Topic</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/DeleteData.cls
public with sharing class DeleteData {
    public DeleteData() {

    }

    public static void PurgeAllData()
    {
        // Cleat account
        List<Account> acc = [SELECT ID FROM Account WHERE Name='Wisdom'];
        delete acc;

        // Clear Quotes
        List<Quote__c> quotes = [SELECT ID FROM Quote__c];
        delete quotes;

        // Clear quote topics
        List<Quote_Topic__c> quoteTopics  = [SELECT ID FROM Quote_Topic__c];
        delete quoteTopics;



    }
}